[project]
name = "temporal-daf-poc"
version = "0.1.0"
description = "Temporal Durable Agent Framework POC"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioconsole>=0.8.1",
    "slack-sdk>=3.35.0",
    "temporalio>=1.11.1",
    "vertexai>=1.71.1",
]
